import type { Metadata } from "next";
import "./globals.css";
import { Fraunces } from 'next/font/google'

const ebGaramond = Fraunces({ subsets: ['latin'], weight: ['400', '700'] })


export const metadata: Metadata = {
  title: "Rolex",
  description: "Generated by Farid Mustafayev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ebGaramond.className}>
        {children}
      </body>
    </html>
  );
}
